package test.io.jsd.training.codingame.bender;

public enum Path {

	TO_SOUTH_FROM_START, //
	TO_EAST_FROM_START, //
	LOOP_BECAUSE_OF_CHARP, //
	LOOP_BECAUSE_OF_X, //
	LOOP_BECAUSE_OF_TIME_OUT, //
	TO_SOUTH_FROM_S_MODIFIER, //
	TO_EAST_FROM_E_MODIFIER, //
	TO_NORTH_FROM_N_MODIFIER, //
	TO_WEST_FROM_W_MODIFIER, //
	TO_WEST_FROM_INVERSOR, //
	TO_SOUTH_FROM_BIER, //
	TO_SOUTH_FROM_T, //
	TO_EAST_INLINE_FROM_START;

}
