
package io.jsd.training.client.ws.trainingcenter.clients.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServiceException", targetNamespace = "http://webservice.centreformation.treeptik.fr/")
public class ServiceException_Exception
    extends Exception
{

	private static final long serialVersionUID = 1L;
    private ServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ServiceException_Exception(String message, ServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ServiceException_Exception(String message, ServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: io.jsd.training.tp.spring.clients.webservice.ServiceException
     */
    public ServiceException getFaultInfo() {
        return faultInfo;
    }

}
