
package io.jsd.training.client.ws.trainingcenter.clients.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FormateurWSService", targetNamespace = "http://webservice.centreformation.treeptik.fr/", wsdlLocation = "http://localhost:8080/CentreFormation/FormateurWS?wsdl")
public class FormateurWSService
    extends Service
{

    private final static URL FORMATEURWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException FORMATEURWSSERVICE_EXCEPTION;
    private final static QName FORMATEURWSSERVICE_QNAME = new QName("http://webservice.centreformation.treeptik.fr/", "FormateurWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CentreFormation/FormateurWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FORMATEURWSSERVICE_WSDL_LOCATION = url;
        FORMATEURWSSERVICE_EXCEPTION = e;
    }

    public FormateurWSService() {
        super(__getWsdlLocation(), FORMATEURWSSERVICE_QNAME);
    }

    public FormateurWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FORMATEURWSSERVICE_QNAME, features);
    }

    public FormateurWSService(URL wsdlLocation) {
        super(wsdlLocation, FORMATEURWSSERVICE_QNAME);
    }

    public FormateurWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FORMATEURWSSERVICE_QNAME, features);
    }

    public FormateurWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FormateurWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FormateurWS
     */
    @WebEndpoint(name = "FormateurWSPort")
    public FormateurWS getFormateurWSPort() {
        return super.getPort(new QName("http://webservice.centreformation.treeptik.fr/", "FormateurWSPort"), FormateurWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FormateurWS
     */
    @WebEndpoint(name = "FormateurWSPort")
    public FormateurWS getFormateurWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.centreformation.treeptik.fr/", "FormateurWSPort"), FormateurWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FORMATEURWSSERVICE_EXCEPTION!= null) {
            throw FORMATEURWSSERVICE_EXCEPTION;
        }
        return FORMATEURWSSERVICE_WSDL_LOCATION;
    }

}
